@startuml
skin rose

title RogueLike Game - Component Diagram
/'
Define components
'/
[Game\nEngine] as GE
[State] as State
[EntityManager] as EM
[Asset manager] as AM
package "Level generation" {
  [MapGenerator] as MG
  [ObjectGenerator] as OG
  [ItemGenerator] AS IG
}
[WorldController] as WC
/'
===================================
'/
EnentHandler <-- GE
Controller <-- EM
Controller <- GE
GE -> GUI
GE --> State
EM <- State 

State --> WC
WC --> MG 
MG --> AM
OG --> AM
IG --> AM
OG <- MG
MG -> IG
@enduml